name: Build and Stage Changes

on:
  push:
    paths:
      - 'argcode.py'  # Theo dõi sự thay đổi của file argcode.py

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build.bat
        run: .\build\build.bat

      - name: Stage changes
        run: git add .
